# Generated by Django 2.2.5 on 2019-09-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MbtaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('can_specify_id', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MbtaInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('associated_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_includes', to='params.MbtaObject')),
                ('included_by', models.ManyToManyField(related_name='includes', to='params.MbtaObject')),
            ],
        ),
        migrations.CreateModel(
            name='MbtaFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('associated_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_filters', to='params.MbtaObject')),
                ('for_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', related_query_name='filter', to='params.MbtaObject')),
            ],
        ),
        migrations.CreateModel(
            name='MbtaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('data_type', models.CharField(max_length=50)),
                ('default', models.CharField(blank=True, max_length=100)),
                ('example', models.CharField(blank=True, max_length=100)),
                ('minimum', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('choices', models.CharField(blank=True, max_length=200)),
                ('data_format', models.CharField(blank=True, max_length=50)),
                ('for_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', related_query_name='attribute', to='params.MbtaObject')),
            ],
        ),
    ]
