# Generated by Django 2.2.5 on 2019-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtaobject',
            name='requires_filters',
            field=models.BooleanField(default=False),
        ),
    ]
