# Generated by Django 2.2.5 on 2019-09-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_mbtaobject_requires_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtaattribute',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mbtafilter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mbtainclude',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mbtaobject',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
