# Generated by Django 2.2.5 on 2019-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0003_auto_20190921_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtaattribute',
            name='json_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
