# Generated by Django 2.2.5 on 2019-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0004_mbtaattribute_json_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtafilter',
            name='json_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
