# Generated by Django 2.2.5 on 2019-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0005_mbtafilter_json_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtaattribute',
            name='choices',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
