# Generated by Django 2.2.5 on 2019-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response_size_bytes',
            field=models.IntegerField(blank=True, null=True, verbose_name='response size'),
        ),
    ]
